name: enigma2-plugins build 3.11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build enigma2-plugins
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc: [12]
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install automake
          sudo apt-get install build-essential
          sudo apt-get install gettext
          sudo apt-get install g++-${{ matrix.gcc }}

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build plugins, gcc-${{ matrix.gcc }}, python 3.11
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          sudo apt-get install python3.11-dev  
          pip3 install six
          # sed -i '/PKG_CHECK_MODULES(ENIGMA2, enigma2)/d' ./configure.ac
          # sed -i '/PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)/d' ./configure.ac
          # sed -i '/AX_PYTHON_DEVEL/d' ./configure.ac
          autoreconf -i
          ./configure --without-debug --with-po
          make
          rm -rf ./subsdownloader2
          python -m compileall .
